[package]
name = "firefly-blutti"
version = "0.11.0"
rust-version = "1.91.0"
edition = "2024"

[dependencies]
firefly-rust = { version = "0.14.0", features = ["alloc", "talc"] }
fixedstr = { version = "0.5.10", features = ["no-alloc"] }
serde = { version = "1.0.228", default-features = false, features = [
    "alloc",
    "derive",
] }
serde_json = { version = "1.0.150", default-features = false, features = [
    "alloc",
] }

# https://github.com/johnthagen/min-sized-rust
[profile.release]
strip = true    # Automatically strip symbols from the binary.
opt-level = "s" # Optimize for speed.
lto = true      # Enable link-time optimization
