use firefly_rust::Badge;

use crate::tile_collider::*;

pub const TILE_WIDTH: i32 = 8;
pub const TILE_HEIGHT: i32 = 8;
pub const SPRITES_H: i32 = 16;
pub const TILES_H: i32 = 30;
pub const HALF_FONT_WIDTH: i32 = 2;
pub const FONT_BASE_LINE: i32 = 4;
pub const LINE_HEIGHT: i32 = 8;
pub const BADGE_STARS: Badge = Badge(1);
pub const BADGE_LEVELS: Badge = Badge(2);
pub const BADGE_DEATHS: Badge = Badge(3);
pub const BLUTTI_RIGHT_SPRITES: [i32; 2] = [114, 115];
pub const BLUTTI_LEFT_SPRITES: [i32; 2] = [112, 113];
pub const BLUTTI_IDLE_RIGHT_SPRITES: [i32; 2] = [118, 119];
pub const BLUTTI_IDLE_LEFT_SPRITES: [i32; 2] = [116, 117];
pub const BLUTTI_JUMP_RIGHT_SPRITES: [i32; 4] = [80, 81, 82, 83];
pub const BLUTTI_JUMP_LEFT_SPRITES: [i32; 4] = [84, 85, 86, 87];
pub const BLUTTI_CLIMB_RIGHT_SPRITES: [i32; 2] = [122, 123];
pub const BLUTTI_CLIMB_LEFT_SPRITES: [i32; 2] = [120, 121];
pub const BLUTTI_DASH_RIGHT_SPRITES: [i32; 4] = [96, 97, 98, 99];
pub const BLUTTI_DASH_LEFT_SPRITES: [i32; 4] = [100, 101, 102, 103];
pub const BLUTTI_DEATH_SPRITES: [i32; 4] = [124, 125, 126, 127];
pub const BLUTTI_EXIT_RIGHT_SPRITES: [i32; 4] = [92, 93, 94, 95];
pub const BLUTTI_EXIT_LEFT_SPRITES: [i32; 4] = [108, 109, 110, 111];
pub const BLUTTI_TURN_RIGHT_SPRITES: [i32; 4] = [71, 72, 73, 74];
pub const BLUTTI_TURN_LEFT_SPRITES: [i32; 4] = [75, 76, 77, 78];
pub const COLLECTION_SPRITES: [i32; 4] = [104, 105, 106, 107];

// Level 0 is a debug level
pub const LEVELS: [&str; 6] = ["level0", "level1", "level2", "level3", "level4", "level5"];

pub const CREDITS: [&str; 8] = [
    "Credits:",
    "Programming: Olle Wreede",
    "Graphics: Olle Wreede",
    "Level design: Olle Wreede",
    "Music: Zane Little Music",
    "SFX: @Shades, Luke.RUSTLTD, sauer2",
    "",
    "Press (E) to go back to game",
];

pub const INFO: [&str; 5] = [
    "Controls:",
    "Press (S) to jump",
    "Press (W) to dash",
    "",
    "Press (E) to go back to game",
];

pub const COLLISION: [TileCollider; 256] = [
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Climbable,
    TileCollider::Star,
    TileCollider::ExtraLife,
    TileCollider::Exit,
    TileCollider::None,
    TileCollider::Deadly,
    TileCollider::Deadly,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Deadly,
    TileCollider::None,
    TileCollider::Full,
    TileCollider::Slippery,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::None,
    TileCollider::None,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::Deadly,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Climbable,
    TileCollider::Full,
    TileCollider::Full,
    TileCollider::Conveyor,
    TileCollider::Conveyor,
    TileCollider::Conveyor,
    TileCollider::Exit,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::Collectible(20),
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
    TileCollider::None,
];
