#[derive(PartialEq, Debug)]
pub enum PlayerState {
    Idle,
    Jumping,
    JumpingLeft,
    JumpingRight,
    JumpingStop,
    DashingLeft,
    DashingRight,
    RunningLeft,
    RunningRight,
    RunningStop,
    ClimbingUp,
    ClimbingDown,
    ClimbingStop,
    ClimbingSideways,
    ClimbingSidewaysStop,
    ClimbingIdle,
    Falling,
    FallingLeft,
    FallingRight,
}
